### PR TITLE
fix: extra fetch to get storage description

### LINKED ISSUE #3: LOAMA does not work when no storage triple present in webID
When the webID does not contain a triple point to the root storage, i.e.`<webID> <http://www.w3.org/ns/pim/space#storage> <podRoot>.`, the application crashes.

There is a way to consistently get this storage description according to the Solid Specification (that is if the WebID is hosted on the pod, if not I am not sure if it is possible to get a storage description URL):
- do a HEAD (or GET request) to the WebID and look for the Link header with field `rel="http://www.w3.org/ns/solid/terms#storageDescription"` (as defined in the [spec section 4.1](https://solidproject.org/TR/protocol#server-storage-description))
- do a GET request to that URL in the Link header. As a result there will be a triple of the following `<rootpod> a <http://www.w3.org/ns/pim/space#Storage> ` (as defined in the [spec section 4.1](https://solidproject.org/TR/protocol#server-storage-description-resource))

Optionally a fallback mechanism can be included that tries multiple approaches to get the root pod.

### PR DESCRIPTION
**Pull request by NuttyShrimp**
closes #3

### CODE REVIEW

File: solid-common-lib/src/index.ts [hunk 1]
```diff
@@ -11,65 +11,94 @@ export { url } from "./types";
...
-        urls.push((new URL('../', session.info.webId!)).toString())
-    }
-    return urls;
+  const webId = session.info.webId!
+  const urls = await getPodUrlAll(webId, {
+    fetch: session.fetch,
+  });
+
+  const fetchedUrl = await fetchStorageTriple(webId);
+  console.log(fetchedUrl)
```
Comment (woutslabbinck) [inline solid-common-lib/src/index.ts]: Can you remove this log statement?

File: solid-common-lib/src/index.ts [hunk 2]
```diff
@@ -11,65 +11,94 @@ export { url } from "./types";
...
-        // TODO this is a guess and should be much more resilient
-        urls.push((new URL('../', session.info.webId!)).toString())
-    }
-    return urls;
+  const webId = session.info.webId!
+  const urls = await getPodUrlAll(webId, {
+    fetch: session.fetch,
+  });
+
+  const fetchedUrl = await fetchStorageTriple(webId);
```
Comment (woutslabbinck) [inline solid-common-lib/src/index.ts]: This call can throw an error, even though the original `getPodUrlAll` is resolving an url. 
An example to test this with is a webId from [inrupt pod spaces](https://start.inrupt.com/profile) ([ESS](https://docs.inrupt.com/ess/latest/)) or [solidcommunity.net ](https://solidcommunity.net/) ([NSS](https://github.com/nodeSolidServer/node-solid-server)).

Only webIDs from Community Solid Servers did not crash `fetchStorageTriple`.

Can you make it so that fetching storages from other solid servers do not crash?

I've tested it with following code:
```js
import { listPodUrls} from 'loama-common'

async function main() {
    // WebID self hosted CSS
    const session = { fetch: fetch, info: {webId: "https://pod.woutslabbinck.com/profile/card#me"}}
    const urls = await listPodUrls(session);
    console.log(urls)

    // WebID from inrupt solid server
    const sessionInrupt = { fetch: fetch, info: {webId: "https://id.inrupt.com/woutslabbinck"}}
    const urlsInrupt = await listPodUrls(sessionInrupt);
    console.log(urlsInrupt)

    // WebID from node solid server
    const sessionNss = { fetch: fetch, info: {webId: "https://woslabbi.solidcommunity.net/profile/card#me"}}
    const urlsNss = await listPodUrls(sessionNss);
    console.log(urlsNss)
}
main()
```

**Review by woutslabbinck — CHANGES_REQUESTED** [review]
Works well now for Solid Pods that do not have a `pim:storage` by default (such as the CSS).

All though, now fetching storages from pods that are not CSS crash now, because of the non existent link header.

Could you change the function `listPodUrls` or `fetchStorageTriple` such that these still work?

Personally, I think it makes most sense to update `fetchStorageTriple` by returning undefined if the link header does not exist. But, it is up to you.

File: solid-common-lib/src/index.ts (hunk 2 above)
Comment (NuttyShrimp) [reply solid-common-lib/src/index.ts]: Should be fixed with the latest commit

**Review by woutslabbinck — APPROVED** [review]
It indeed works as intended now.
